# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/darkdiable/Desktop/1714game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/darkdiable/Desktop/1714game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/darkdiable/Desktop/1714game/CMakeFiles /home/darkdiable/Desktop/1714game/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/darkdiable/Desktop/1714game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 1714game

# Build rule for target.
1714game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 1714game
.PHONY : 1714game

# fast build rule for target.
1714game/fast:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/build
.PHONY : 1714game/fast

src/Box.o: src/Box.cc.o
.PHONY : src/Box.o

# target to build an object file
src/Box.cc.o:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Box.cc.o
.PHONY : src/Box.cc.o

src/Box.i: src/Box.cc.i
.PHONY : src/Box.i

# target to preprocess a source file
src/Box.cc.i:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Box.cc.i
.PHONY : src/Box.cc.i

src/Box.s: src/Box.cc.s
.PHONY : src/Box.s

# target to generate assembly for a file
src/Box.cc.s:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Box.cc.s
.PHONY : src/Box.cc.s

src/Controller.o: src/Controller.cc.o
.PHONY : src/Controller.o

# target to build an object file
src/Controller.cc.o:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Controller.cc.o
.PHONY : src/Controller.cc.o

src/Controller.i: src/Controller.cc.i
.PHONY : src/Controller.i

# target to preprocess a source file
src/Controller.cc.i:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Controller.cc.i
.PHONY : src/Controller.cc.i

src/Controller.s: src/Controller.cc.s
.PHONY : src/Controller.s

# target to generate assembly for a file
src/Controller.cc.s:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Controller.cc.s
.PHONY : src/Controller.cc.s

src/DrawableObject.o: src/DrawableObject.cc.o
.PHONY : src/DrawableObject.o

# target to build an object file
src/DrawableObject.cc.o:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/DrawableObject.cc.o
.PHONY : src/DrawableObject.cc.o

src/DrawableObject.i: src/DrawableObject.cc.i
.PHONY : src/DrawableObject.i

# target to preprocess a source file
src/DrawableObject.cc.i:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/DrawableObject.cc.i
.PHONY : src/DrawableObject.cc.i

src/DrawableObject.s: src/DrawableObject.cc.s
.PHONY : src/DrawableObject.s

# target to generate assembly for a file
src/DrawableObject.cc.s:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/DrawableObject.cc.s
.PHONY : src/DrawableObject.cc.s

src/Estat.o: src/Estat.cc.o
.PHONY : src/Estat.o

# target to build an object file
src/Estat.cc.o:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Estat.cc.o
.PHONY : src/Estat.cc.o

src/Estat.i: src/Estat.cc.i
.PHONY : src/Estat.i

# target to preprocess a source file
src/Estat.cc.i:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Estat.cc.i
.PHONY : src/Estat.cc.i

src/Estat.s: src/Estat.cc.s
.PHONY : src/Estat.s

# target to generate assembly for a file
src/Estat.cc.s:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Estat.cc.s
.PHONY : src/Estat.cc.s

src/Fight.o: src/Fight.cc.o
.PHONY : src/Fight.o

# target to build an object file
src/Fight.cc.o:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Fight.cc.o
.PHONY : src/Fight.cc.o

src/Fight.i: src/Fight.cc.i
.PHONY : src/Fight.i

# target to preprocess a source file
src/Fight.cc.i:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Fight.cc.i
.PHONY : src/Fight.cc.i

src/Fight.s: src/Fight.cc.s
.PHONY : src/Fight.s

# target to generate assembly for a file
src/Fight.cc.s:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Fight.cc.s
.PHONY : src/Fight.cc.s

src/Graphic.o: src/Graphic.cc.o
.PHONY : src/Graphic.o

# target to build an object file
src/Graphic.cc.o:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Graphic.cc.o
.PHONY : src/Graphic.cc.o

src/Graphic.i: src/Graphic.cc.i
.PHONY : src/Graphic.i

# target to preprocess a source file
src/Graphic.cc.i:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Graphic.cc.i
.PHONY : src/Graphic.cc.i

src/Graphic.s: src/Graphic.cc.s
.PHONY : src/Graphic.s

# target to generate assembly for a file
src/Graphic.cc.s:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Graphic.cc.s
.PHONY : src/Graphic.cc.s

src/Joc.o: src/Joc.cc.o
.PHONY : src/Joc.o

# target to build an object file
src/Joc.cc.o:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Joc.cc.o
.PHONY : src/Joc.cc.o

src/Joc.i: src/Joc.cc.i
.PHONY : src/Joc.i

# target to preprocess a source file
src/Joc.cc.i:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Joc.cc.i
.PHONY : src/Joc.cc.i

src/Joc.s: src/Joc.cc.s
.PHONY : src/Joc.s

# target to generate assembly for a file
src/Joc.cc.s:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Joc.cc.s
.PHONY : src/Joc.cc.s

src/Logic.o: src/Logic.cc.o
.PHONY : src/Logic.o

# target to build an object file
src/Logic.cc.o:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Logic.cc.o
.PHONY : src/Logic.cc.o

src/Logic.i: src/Logic.cc.i
.PHONY : src/Logic.i

# target to preprocess a source file
src/Logic.cc.i:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Logic.cc.i
.PHONY : src/Logic.cc.i

src/Logic.s: src/Logic.cc.s
.PHONY : src/Logic.s

# target to generate assembly for a file
src/Logic.cc.s:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Logic.cc.s
.PHONY : src/Logic.cc.s

src/Map.o: src/Map.cc.o
.PHONY : src/Map.o

# target to build an object file
src/Map.cc.o:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Map.cc.o
.PHONY : src/Map.cc.o

src/Map.i: src/Map.cc.i
.PHONY : src/Map.i

# target to preprocess a source file
src/Map.cc.i:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Map.cc.i
.PHONY : src/Map.cc.i

src/Map.s: src/Map.cc.s
.PHONY : src/Map.s

# target to generate assembly for a file
src/Map.cc.s:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Map.cc.s
.PHONY : src/Map.cc.s

src/Minigaem1.o: src/Minigaem1.cpp.o
.PHONY : src/Minigaem1.o

# target to build an object file
src/Minigaem1.cpp.o:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Minigaem1.cpp.o
.PHONY : src/Minigaem1.cpp.o

src/Minigaem1.i: src/Minigaem1.cpp.i
.PHONY : src/Minigaem1.i

# target to preprocess a source file
src/Minigaem1.cpp.i:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Minigaem1.cpp.i
.PHONY : src/Minigaem1.cpp.i

src/Minigaem1.s: src/Minigaem1.cpp.s
.PHONY : src/Minigaem1.s

# target to generate assembly for a file
src/Minigaem1.cpp.s:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Minigaem1.cpp.s
.PHONY : src/Minigaem1.cpp.s

src/MinigaemFitIt.o: src/MinigaemFitIt.cpp.o
.PHONY : src/MinigaemFitIt.o

# target to build an object file
src/MinigaemFitIt.cpp.o:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/MinigaemFitIt.cpp.o
.PHONY : src/MinigaemFitIt.cpp.o

src/MinigaemFitIt.i: src/MinigaemFitIt.cpp.i
.PHONY : src/MinigaemFitIt.i

# target to preprocess a source file
src/MinigaemFitIt.cpp.i:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/MinigaemFitIt.cpp.i
.PHONY : src/MinigaemFitIt.cpp.i

src/MinigaemFitIt.s: src/MinigaemFitIt.cpp.s
.PHONY : src/MinigaemFitIt.s

# target to generate assembly for a file
src/MinigaemFitIt.cpp.s:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/MinigaemFitIt.cpp.s
.PHONY : src/MinigaemFitIt.cpp.s

src/MovileObject.o: src/MovileObject.cc.o
.PHONY : src/MovileObject.o

# target to build an object file
src/MovileObject.cc.o:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/MovileObject.cc.o
.PHONY : src/MovileObject.cc.o

src/MovileObject.i: src/MovileObject.cc.i
.PHONY : src/MovileObject.i

# target to preprocess a source file
src/MovileObject.cc.i:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/MovileObject.cc.i
.PHONY : src/MovileObject.cc.i

src/MovileObject.s: src/MovileObject.cc.s
.PHONY : src/MovileObject.s

# target to generate assembly for a file
src/MovileObject.cc.s:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/MovileObject.cc.s
.PHONY : src/MovileObject.cc.s

src/PilaEstats.o: src/PilaEstats.cpp.o
.PHONY : src/PilaEstats.o

# target to build an object file
src/PilaEstats.cpp.o:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/PilaEstats.cpp.o
.PHONY : src/PilaEstats.cpp.o

src/PilaEstats.i: src/PilaEstats.cpp.i
.PHONY : src/PilaEstats.i

# target to preprocess a source file
src/PilaEstats.cpp.i:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/PilaEstats.cpp.i
.PHONY : src/PilaEstats.cpp.i

src/PilaEstats.s: src/PilaEstats.cpp.s
.PHONY : src/PilaEstats.s

# target to generate assembly for a file
src/PilaEstats.cpp.s:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/PilaEstats.cpp.s
.PHONY : src/PilaEstats.cpp.s

src/Player.o: src/Player.cc.o
.PHONY : src/Player.o

# target to build an object file
src/Player.cc.o:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Player.cc.o
.PHONY : src/Player.cc.o

src/Player.i: src/Player.cc.i
.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cc.i:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Player.cc.i
.PHONY : src/Player.cc.i

src/Player.s: src/Player.cc.s
.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cc.s:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/Player.cc.s
.PHONY : src/Player.cc.s

src/SceneNode.o: src/SceneNode.cpp.o
.PHONY : src/SceneNode.o

# target to build an object file
src/SceneNode.cpp.o:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/SceneNode.cpp.o
.PHONY : src/SceneNode.cpp.o

src/SceneNode.i: src/SceneNode.cpp.i
.PHONY : src/SceneNode.i

# target to preprocess a source file
src/SceneNode.cpp.i:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/SceneNode.cpp.i
.PHONY : src/SceneNode.cpp.i

src/SceneNode.s: src/SceneNode.cpp.s
.PHONY : src/SceneNode.s

# target to generate assembly for a file
src/SceneNode.cpp.s:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/SceneNode.cpp.s
.PHONY : src/SceneNode.cpp.s

src/SplashImage.o: src/SplashImage.cc.o
.PHONY : src/SplashImage.o

# target to build an object file
src/SplashImage.cc.o:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/SplashImage.cc.o
.PHONY : src/SplashImage.cc.o

src/SplashImage.i: src/SplashImage.cc.i
.PHONY : src/SplashImage.i

# target to preprocess a source file
src/SplashImage.cc.i:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/SplashImage.cc.i
.PHONY : src/SplashImage.cc.i

src/SplashImage.s: src/SplashImage.cc.s
.PHONY : src/SplashImage.s

# target to generate assembly for a file
src/SplashImage.cc.s:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/SplashImage.cc.s
.PHONY : src/SplashImage.cc.s

src/SpriteNode.o: src/SpriteNode.cpp.o
.PHONY : src/SpriteNode.o

# target to build an object file
src/SpriteNode.cpp.o:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/SpriteNode.cpp.o
.PHONY : src/SpriteNode.cpp.o

src/SpriteNode.i: src/SpriteNode.cpp.i
.PHONY : src/SpriteNode.i

# target to preprocess a source file
src/SpriteNode.cpp.i:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/SpriteNode.cpp.i
.PHONY : src/SpriteNode.cpp.i

src/SpriteNode.s: src/SpriteNode.cpp.s
.PHONY : src/SpriteNode.s

# target to generate assembly for a file
src/SpriteNode.cpp.s:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/SpriteNode.cpp.s
.PHONY : src/SpriteNode.cpp.s

src/TextNode.o: src/TextNode.cpp.o
.PHONY : src/TextNode.o

# target to build an object file
src/TextNode.cpp.o:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/TextNode.cpp.o
.PHONY : src/TextNode.cpp.o

src/TextNode.i: src/TextNode.cpp.i
.PHONY : src/TextNode.i

# target to preprocess a source file
src/TextNode.cpp.i:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/TextNode.cpp.i
.PHONY : src/TextNode.cpp.i

src/TextNode.s: src/TextNode.cpp.s
.PHONY : src/TextNode.s

# target to generate assembly for a file
src/TextNode.cpp.s:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/TextNode.cpp.s
.PHONY : src/TextNode.cpp.s

src/main.o: src/main.cc.o
.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) -f CMakeFiles/1714game.dir/build.make CMakeFiles/1714game.dir/src/main.cc.s
.PHONY : src/main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... 1714game"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/Box.o"
	@echo "... src/Box.i"
	@echo "... src/Box.s"
	@echo "... src/Controller.o"
	@echo "... src/Controller.i"
	@echo "... src/Controller.s"
	@echo "... src/DrawableObject.o"
	@echo "... src/DrawableObject.i"
	@echo "... src/DrawableObject.s"
	@echo "... src/Estat.o"
	@echo "... src/Estat.i"
	@echo "... src/Estat.s"
	@echo "... src/Fight.o"
	@echo "... src/Fight.i"
	@echo "... src/Fight.s"
	@echo "... src/Graphic.o"
	@echo "... src/Graphic.i"
	@echo "... src/Graphic.s"
	@echo "... src/Joc.o"
	@echo "... src/Joc.i"
	@echo "... src/Joc.s"
	@echo "... src/Logic.o"
	@echo "... src/Logic.i"
	@echo "... src/Logic.s"
	@echo "... src/Map.o"
	@echo "... src/Map.i"
	@echo "... src/Map.s"
	@echo "... src/Minigaem1.o"
	@echo "... src/Minigaem1.i"
	@echo "... src/Minigaem1.s"
	@echo "... src/MinigaemFitIt.o"
	@echo "... src/MinigaemFitIt.i"
	@echo "... src/MinigaemFitIt.s"
	@echo "... src/MovileObject.o"
	@echo "... src/MovileObject.i"
	@echo "... src/MovileObject.s"
	@echo "... src/PilaEstats.o"
	@echo "... src/PilaEstats.i"
	@echo "... src/PilaEstats.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/SceneNode.o"
	@echo "... src/SceneNode.i"
	@echo "... src/SceneNode.s"
	@echo "... src/SplashImage.o"
	@echo "... src/SplashImage.i"
	@echo "... src/SplashImage.s"
	@echo "... src/SpriteNode.o"
	@echo "... src/SpriteNode.i"
	@echo "... src/SpriteNode.s"
	@echo "... src/TextNode.o"
	@echo "... src/TextNode.i"
	@echo "... src/TextNode.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

